### ISSUE TITLE
ShareKit-Demo-App not working

### ISSUE THREAD

**Issue by riksof-abdulrauf** [ShareKit/ShareKit-Demo-App#2]
I have clone the project then run

```
   pod install
```

getting files ( ShareKit.h, SHK.h)not found error
![screen shot 2016-02-22 at 8 27 26 pm](https://cloud.githubusercontent.com/assets/5626513/13222688/e88e04e4-d9a2-11e5-8687-f30e25581eed.png)
![screen shot 2016-02-22 at 8 29 40 pm](https://cloud.githubusercontent.com/assets/5626513/13222746/381d33ae-d9a3-11e5-87a4-959f474ef4bb.png)

**Comment by VilemKurz** [comment]
You tried the "ShareKit Demo App" target, but the one you probably needed to run is  "ShareKit Demo App (CocoaPods)".

FYI the ShareKit Demo App needs ShareKit lib files delivered via submodule
